name: mobile
description: Tela application de la plateforme immobiliere TELA CI
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+60

environment:
  sdk: '>=3.1.0 <4.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter

  rxdart: ^0.27.7
  path_provider: ^2.1.1
  permission_handler: ^11.0.1
  # image picher
  image_picker: ^1.0.4
  # Stacked package and friends
  stacked: ^3.4.1+1
  stacked_services: ^1.3.0
  flutter_local_notifications: ^16.1.0
  shared_preferences: ^2.2.2
  webview_flutter: ^4.4.2
  cinetpay: ^1.0.7
  get: ^4.6.6
  video_player: ^2.8.1
  intl: ^0.18.1
  marquee: ^2.2.3
  file_picker: ^6.1.1
  web_socket_channel: ^2.2.0
  mime: ^1.0.4
  camera:
  country_picker:
  #  camera:

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  pdf: ^3.10.7
  printing: ^5.11.1
  url_launcher: ^6.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  #  auto_route_generator: ^2.4.1
  build_runner:
  stacked_generator: ^1.5.1

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/logo.png"
  adaptive_icon_background: #ffffff

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/images/logo.png
    - assets/images/logo_2.png
    - assets/images/pub.png
    - assets/images/sport.png
    - assets/images/film.png
    - assets/images/live.png
    - assets/images/exclu.png
    - assets/images/differe.png
    - assets/images/acc1.jpg
    - assets/images/acc2.jpg
    - assets/images/acc3.jpg
    - assets/images/acc4.jpg
    - assets/images/acc5.jpg
    - assets/images/sport.jpg
    - assets/images/films.jpg
    - assets/images/live.jpg
    - assets/images/différé.jpg
    - assets/images/rediffusion.jpg
    - assets/images/pub.jpg
    - assets/images/p1.webp
    - assets/images/p2.webp
    - assets/images/p3.webp
    - assets/images/p4.webp
    - assets/images/p5.webp
    - assets/images/telatv-logo.jpg
    - assets/images/tela_tv_logo.png
    - assets/images/fond_fin.jpg
    - assets/images/diféré.jpg
    - assets/images/pere_noel.jpg
    - assets/images/1000_maisons.jpg
    - assets/images/jn.jpg
    - assets/images/Bonne.jpeg
    - assets/images/pack.png



  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
flutter_intl:
  enabled: true
